IBM/ibm-spectrum-scale-cloud-install

README.md
- Updated readme with latest terraform version
- Corrected the JSON syntax shown in the README example.
Closes #2
=> Update README with latest terraform version and Fix JSON example

README.md, resources/aws/compute/ec2/create.tf, resources/aws/storage/ebs_attach/ebs_attach.tf
=> Add lifecycle for instances to avoid instance replacement

resources/aws/compute/ec2/create.tf
This change is made to support large user_data
Closes #3
=> Change EC2 user_data to template_cloudinit_config

resources/aws/compute/ec2/create.tf
=> Fix missing type conversion

aws_scale_templates/sub_modules/vpc_template/aws_scale_vpc.tf, resources/aws/network/route/route.tf
=> Fix aws_route resource to toggle gateway_id, nat_gateway_id

resources/common/ansible_scale_playbook/prepare_scale_inv.py
=> Patch to fix automount, metadatareplicas, failure group assignment

aws_scale_templates/tf_backend/create_tf_state_bucket.tf
=> Add bucket id as output parameter

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_variables.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf, resources/common/ansible_scale_playbook/ansible_scale_playbook.tf, resources/common/ansible_scale_playbook/backup_ansible_inv.py
=> Add support for backing up ansible inventory json

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_output.tf, resources/aws/compute/ec2/create.tf
=> Update templates to output s3 bucket, stack name, install boto3

resources/aws/compute/ec2/create.tf
=> Add terraform, git and boto3 dependency to ec2 metadata

resources/common/ansible_scale_playbook/ansible_scale_playbook.tf, resources/common/ansible_scale_playbook/backup_to_backend.py
=> Add backup of keyring

resources/aws/compute/ec2/create.tf
=> Add PyYaml dependency

resources/common/ansible_scale_playbook/prepare_scale_inv.py
=> Explict declaration of state flag ansible scale inventory json

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf
=> Fix the variable name change

resources/common/ansible_scale_playbook/ansible_scale_playbook.tf, resources/common/generate_keys/generate_keys.tf
=> Add lock in the generate keys

README.md, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_variables.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_output.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf, docs/aws.md, docs/gen/aws_existing_vpc/README.md, docs/gen/aws_new_vpc/README.md, resources/aws/compute/ec2/create.tf, resources/common/ansible_scale_playbook/ansible_scale_playbook.tf, resources/common/generate_keys/generate_keys.tf
=> Remove ansible-vault for ssh key storage

resources/common/ansible_scale_playbook/prepare_scale_inv.py
The cluster name fqdn format;
<stack_name>.<region>.compute.internal.com
=> Remove region name from clustername

resources/aws/compute/ec2/create.tf
=> Extend Ec2 user-metadata to Ubuntu, Suse

README.md, docs/gcp.md, gcp_scale_templates/gcp_new_vpc_scale/gcp_new_vpc_scale.tf, gcp_scale_templates/gcp_new_vpc_scale/gcp_new_vpc_scale_output.tf, gcp_scale_templates/gcp_new_vpc_scale/gcp_new_vpc_scale_provider.tf, gcp_scale_templates/gcp_new_vpc_scale/gcp_new_vpc_scale_variables.tf, gcp_scale_templates/sub_modules/bastion_template/gcp_scale_bastion.tf, gcp_scale_templates/sub_modules/bastion_template/gcp_scale_bastion_outputs.tf, gcp_scale_templates/sub_modules/bastion_template/gcp_scale_bastion_provider.tf, gcp_scale_templates/sub_modules/bastion_template/gcp_scale_bastion_variables.tf, gcp_scale_templates/sub_modules/instance_template/gcp_scale_instances.tf, gcp_scale_templates/sub_modules/instance_template/gcp_scale_instances_output.tf, gcp_scale_templates/sub_modules/instance_template/gcp_scale_instances_provider.tf, gcp_scale_templates/sub_modules/instance_template/gcp_scale_instances_variables.tf, gcp_scale_templates/sub_modules/vpc_template/gcp_scale_vpc.tf, gcp_scale_templates/sub_modules/vpc_template/gcp_scale_vpc_outputs.tf, gcp_scale_templates/sub_modules/vpc_template/gcp_scale_vpc_provider.tf, gcp_scale_templates/sub_modules/vpc_template/gcp_scale_vpc_variables.tf, resources/gcp/compute_engine/bastion_instance/bastion_instance.tf, resources/gcp/compute_engine/vm_instance/vm_instance_0_disk/vm_instance.tf, resources/gcp/compute_engine/vm_instance/vm_instance_1_disk/vm_instance.tf, resources/gcp/compute_engine/vm_instance/vm_instance_multiple_zones/vm_instance.tf, resources/gcp/network/firewall/allow_bastion/allow_bastion.tf, resources/gcp/network/firewall/allow_internal/allow_internal.tf, resources/gcp/network/subnet/subnet.tf, resources/gcp/storage/compute_disk_attach/compute_disk_attach.tf, resources/gcp/storage/compute_disk_create/compute_disk_create.tf, resources/gcp/vpc/vpc.tf
=> Initial commit for GCP platform addition

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/sub_modules/bastion_template/aws_scale_bastion_outputs.tf, resources/aws/asg/asg_group/asg_group.tf
=> Identify bastion instance ip and provide it as part of output

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/sub_modules/bastion_template/aws_scale_bastion_outputs.tf, resources/aws/asg/asg_group/asg_group.tf, resources/aws/compute/ec2/create.tf, resources/aws/storage/ebs_create/ebs_create.tf
1. Bump terraform version
2. Provide Bastion ip as part of output
=> Merge dev to master

resources/aws/compute/ec2/create.tf, resources/common/ansible_scale_playbook/ansible_scale_playbook.tf, resources/common/ansible_scale_playbook/prepare_scale_inv.py, resources/common/ansible_scale_playbook/wait_instance_ok_state.py
=> Adding tuning parameters/profiles

aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/vpc_template/aws_scale_vpc.tf, aws_scale_templates/sub_modules/vpc_template/aws_scale_vpc_variables.tf
=> Add support for 3AZ

aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf, resources/aws/compute/ec2/create.tf
Reverts IBM/ibm-spectrum-scale-cloud-install#130
=> Revert "Remove root volume size restriction"

resources/common/ansible_scale_playbook/prepare_scale_inv.py
Define the correct number of quorum nodes in the inventory file
=> Fix for issue #175. Defining the correct number of quorum nodes

resources/aws/compute/ec2/create.tf, resources/common/ansible_scale_playbook/prepare_scale_inv.py, resources/common/generate_keys/generate_keys.tf
Terraform auto deletes and recreates instances if it finds that there are "holes" in the state file resource indexes (after a terraform delete operation). This fix enables the prevention of this behaviour.
=> Fix to ensure Terraform does not auto delete and recreate instances

resources/aws/compute/ec2/create.tf
Enable AWS yum repositories if ec2 instance boots with no default yum repository enabled
=> Enable default AWS yum repositories

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_variables.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf
Generates ansible inventory JSON by default (can be controlled by the `generate_ansible_inv` parameter.
=> Generate ansible inventory JSON by default

resources/aws/compute/ec2/create.tf, resources/common/ansible_scale_playbook/wait_instance_ok_state.py
Add retry capability to user data install and key retrieval. Increase wait limit to 20 minutes for instances to be up and 15 minutes fr provisioning.
=> Add retry capability to user data install and key retrieval

resources/aws/ssm/ssm_parameter_store.tf, resources/aws/ssm/ssm_putparams.py
* [AWS] Add retry for SSM upload
=> [AWS] Add retry for SSM upload (#169)

aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_outputs.tf, aws_scale_templates/aws_new_vpc_scale/aws_new_vpc_scale_variables.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf
=> [AWS] Update with jump host setting

aws_scale_templates/sub_modules/instance_template/aws_scale_instances.tf, aws_scale_templates/sub_modules/instance_template/aws_scale_instances_variables.tf, resources/aws/compute/ec2/create.tf
=> [AWS] Remove root volume size restriction

ibmcloud_scale_templates/sub_modules/vpc_template/ibmcloud_scale_vpc.tf
Delay VPC address prefix getting destroyed.
=> Add dependencies for terraform destroy

ibmcloud_scale_templates/ibmcloud_new_vpc_scale/ibmcloud_new_vpc_scale.tf, ibmcloud_scale_templates/ibmcloud_new_vpc_scale/ibmcloud_new_vpc_scale_variables.tf, ibmcloud_scale_templates/sub_modules/instance_template/ibmcloud_scale_instances.tf, ibmcloud_scale_templates/sub_modules/instance_template/ibmcloud_scale_instances_variables.tf, resources/ibmcloud/compute/bastion_vsi/bastion_vsi.tf, resources/ibmcloud/compute/scale_vsi_0_vol/scale_vsi_0_vol.tf, resources/ibmcloud/compute/scale_vsi_multiple_vol/scale_vsi_multiple_vol.tf
The "instances_ssh_user" should be used as the user name.
=> Create new user on compute and storage instances

aws_scale_templates/aws_new_vpc_scale/README.md, resources/aws/compute/ec2_0_vol/ec2_0_vol.tf, resources/aws/compute/ec2_multiple_vol/ec2_multiple_vol.tf, resources/common/compute_configuration/compute_configuration.tf, resources/common/scale_configuration/scale_configuration.tf, resources/common/storage_configuration/storage_configuration.tf
=> [AWS] Improvements to use for_each

resources/common/scripts/prepare_scale_inv.py
=> Fix quorum allocations

resources/common/scripts/prepare_scale_inv.py
=> Fix storage cluster gui in multi-az
